import "./globals.css";
import Navbar from "./(componenets)/Navbar";
import AuthProvider from "./(componenets)/AuthProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-gray-100">
        <AuthProvider>
        <Navbar />
        <div className="m-2">{children}</div>
        </AuthProvider>
      </body>
    </html>
  );
}
